
[font]
size = 13.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 0.8

[keyboard]
bindings = [
{ key = "N", mods = "Control", action = "CreateNewWindow" },
]

[general]
live_config_reload = true
import = ["/home/simon/.config/alacritty/gruvbox-dark.toml"]
